"""add_vectorization_fields_to_document

Revision ID: f014e35f1fe0
Revises: 
Create Date: 2025-10-08 12:55:20.693647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f014e35f1fe0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_vectorized', sa.Boolean(), nullable=True, comment='是否已向量化'))
    op.add_column('documents', sa.Column('vectorized_at', sa.DateTime(timezone=True), nullable=True, comment='向量化完成时间'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'vectorized_at')
    op.drop_column('documents', 'is_vectorized')
    # ### end Alembic commands ###