"""Add description field to Document model

Revision ID: 6843bf8e7ec1
Revises: f014e35f1fe0
Create Date: 2025-10-08 14:17:10.051339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6843bf8e7ec1'
down_revision = 'f014e35f1fe0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('description', sa.Text(), nullable=True, comment='文档描述'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'description')
    # ### end Alembic commands ###